# Netlify Configuration - Frame Economics

# Redirect HTTP to HTTPS (both www and non-www)
[[redirects]]
  from = "http://icecoldfroste.com/*"
  to = "https://icecoldfroste.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.icecoldfroste.com/*"
  to = "https://icecoldfroste.com/:splat"
  status = 301
  force = true

# Redirect HTTPS www to non-www
[[redirects]]
  from = "https://www.icecoldfroste.com/*"
  to = "https://icecoldfroste.com/:splat"
  status = 301
  force = true

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.19.5"
  
# Enable Next.js static export
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Function-specific configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "nft"

# API function redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
