# Netlify Configuration - Frame Economics

# Redirect www to non-www (HTTPS only)
[[redirects]]
  from = "https://www.icecoldfroste.com/*"
  to = "https://icecoldfroste.com/:splat"
  status = 301
  force = true

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# Function-specific configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "nft"

# API function redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
